[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
;addons_path = /Users/PC4FIX/Desktop/Odoo_Project/custom_addons,/Users/PC4FIX/Desktop/Odoo_Project/odoo_v15/addons
